# Generated by Django 5.0.3 on 2026-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
