from django.urls import path

from .investor_dashboard import InvestorDashboardView
from .views import (
    AnalyseDetailView,
    AnalyseListView,
    AnalyseParcellesView,
    AnalyseResultatsView,
    AnalyseTerrainView,
    CoucheDetail,
    CoucheList,
    ProjetDetailView,
    ProjetListView,
    TerrainDetailView,
    TerrainListView,
    TypeProjetListView,
    couche_features_create,
    couche_features_delete,
    couche_features_duplicate,
    couche_features_list,
    couche_features_update,
    importer_couche,
    telecharger_couche,
)

urlpatterns = [
    path('types/', TypeProjetListView.as_view(), name='projets-types'),
    path('investor-dashboard/', InvestorDashboardView.as_view(), name='investor-dashboard'),
    path('', ProjetListView.as_view(), name='projets-list'),
    path('<int:pk>/', ProjetDetailView.as_view(), name='projets-detail'),
    path('<int:projet_pk>/terrains/', TerrainListView.as_view(), name='terrains-list'),
    path('<int:projet_pk>/terrains/<int:pk>/', TerrainDetailView.as_view(), name='terrains-detail'),
    path('<int:projet_pk>/analyser/', AnalyseTerrainView.as_view(), name='terrains-analyse'),
    path('<int:projet_pk>/analyser-parcelles/', AnalyseParcellesView.as_view(), name='parcelles-analyse'),
    path('<int:projet_pk>/analyses/', AnalyseListView.as_view(), name='analyses-list'),
    path('<int:projet_pk>/analyses/<int:analyse_pk>/', AnalyseDetailView.as_view(), name='analyses-detail'),
    path('<int:projet_pk>/analyses/<int:analyse_pk>/resultats/', AnalyseResultatsView.as_view(), name='analyses-resultats'),
    path('couches/', CoucheList.as_view(), name='couche-list'),
    path('couches/<int:pk>/', CoucheDetail.as_view(), name='couche-detail'),
    path('couches/<int:pk>/import/', importer_couche, name='couche-import'),
    path('couches/<int:pk>/download/', telecharger_couche, name='couche-download'),
    path('couches/<int:pk>/features/', couche_features_list, name='couche-features-list'),
    path('couches/<int:pk>/features/create/', couche_features_create, name='couche-features-create'),
    path('couches/<int:pk>/features/<int:feature_id>/update/', couche_features_update, name='couche-features-update'),
    path('couches/<int:pk>/features/<int:feature_id>/delete/', couche_features_delete, name='couche-features-delete'),
    path('couches/<int:pk>/features/<int:feature_id>/duplicate/', couche_features_duplicate, name='couche-features-duplicate'),
]
