# Generated by Django 5.0.3 on 2026-08-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20)),
                ('entite', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('projet', 'Projet'), ('terrain', 'Terrain'), ('analyse', 'Analyse'), ('couche', 'Couche'), ('message', 'Message'), ('reponse', 'Réponse')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'activite',
                'ordering': ['-date_creation'],
            },
        ),
    ]
