# Generated by Django 5.0.3 on 2026-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_utilisateurs', models.IntegerField(default=0)),
                ('nb_utilisateurs_actifs', models.IntegerField(default=0)),
                ('nb_utilisateurs_actifs_aujourdhui', models.IntegerField(default=0)),
                ('nb_utilisateurs_nouveaux', models.IntegerField(default=0)),
                ('nb_utilisateurs_desactives', models.IntegerField(default=0)),
                ('par_role', models.JSONField(default=dict)),
                ('nb_couches_total', models.IntegerField(default=0)),
                ('nb_couches_ajoutees', models.IntegerField(default=0)),
                ('nb_couches_modifiees', models.IntegerField(default=0)),
                ('nb_couches_supprimees', models.IntegerField(default=0)),
                ('evolution_couches', models.JSONField(default=list)),
                ('nb_analyses', models.IntegerField(default=0)),
                ('nb_analyses_semaine', models.IntegerField(default=0)),
                ('evolution_analyses', models.JSONField(default=list)),
                ('nb_projets', models.IntegerField(default=0)),
                ('nb_messages', models.IntegerField(default=0)),
                ('nb_notifications_non_lues', models.IntegerField(default=0)),
                ('nb_parcelles_cadastre', models.IntegerField(default=0)),
                ('nb_activite_total', models.IntegerField(default=0)),
                ('evolution_activite', models.JSONField(default=list)),
                ('par_entite', models.JSONField(default=dict)),
                ('evolution_utilisateurs', models.JSONField(default=list)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistiques tableau de bord',
                'verbose_name_plural': 'Statistiques tableau de bord',
                'db_table': 'dashboard_stats',
            },
        ),
    ]
