# Generated by Django 6.0.7 on 2026-07-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('type_notif', models.CharField(choices=[('nouveau_message', 'Nouveau message'), ('nouvelle_reponse', 'Nouvelle réponse'), ('message_modifie', 'Message modifié'), ('message_supprime', 'Message supprimé'), ('reponse_modifiee', 'Réponse modifiée'), ('reponse_supprimee', 'Réponse supprimée')], max_length=50)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
