# Generated by Django 6.0.7 on 2026-07-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
