# Generated by Django 5.0.3 on 2026-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('slug', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knowledge_entries',
                'ordering': ['slug'],
            },
        ),
    ]
