# Generated by Django 6.0.7 on 2026-07-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_defaut', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'type_projet',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('surface_souhaitee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nombre_unites', models.IntegerField(blank=True, null=True)),
                ('surface_construite', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_construction', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('autres_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prix_vente_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revenu_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('investisseur', models.ForeignKey(db_column='investisseur_id', on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='accounts.utilisateur')),
                ('id_type', models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='projets.typeprojet')),
            ],
            options={
                'db_table': 'projet',
                'ordering': ['-date_creation'],
            },
        ),
    ]
