# Generated by Django 6.0.7 on 2026-07-29 12:39

import django.db.models.deletion
import projets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_seed_typeprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_affichage', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_geometrie', models.CharField(blank=True, max_length=50)),
                ('attributs', models.JSONField(blank=True, default=list)),
                ('table_liee', models.CharField(blank=True, max_length=100)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=projets.models.couche_upload_path)),
                ('taille_fichier', models.BigIntegerField(blank=True, null=True)),
                ('format_fichier', models.CharField(blank=True, max_length=20)),
                ('etat', models.CharField(choices=[('non_importe', 'Non importé'), ('importe', 'Importé'), ('erreur', 'Erreur')], default='non_importe', max_length=20)),
                ('message_erreur', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'couche',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ImportCouche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.CharField(max_length=500)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('erreur', 'Erreur')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('nb_enregistrements', models.IntegerField(blank=True, null=True)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('couche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='projets.couche')),
            ],
            options={
                'db_table': 'import_couche',
                'ordering': ['-date_import'],
            },
        ),
    ]
