# Generated by Django 6.0.7 on 2026-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_couche_importcouche'),
    ]

    operations = [
        migrations.AddField(
            model_name='couche',
            name='categorie',
            field=models.CharField(blank=True, choices=[('foncier', 'Foncier'), ('urbanisme', 'Urbanisme'), ('administratif', 'Administratif'), ('equipements', 'Équipements'), ('infrastructure', 'Infrastructure'), ('topographie', 'Topographie')], default='', max_length=50),
        ),
    ]
