# Generated by Django 6.0.7 on 2026-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_seed_highway_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='prix_terrain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
