# Generated by Django 6.0.7 on 2026-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0010_projet_prix_terrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelleCadastrale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parcelle', models.CharField(max_length=50, unique=True)),
                ('num_titre_foncier', models.CharField(blank=True, max_length=100, null=True)),
                ('type_immatriculation', models.CharField(blank=True, max_length=100)),
                ('nature_juridique', models.CharField(blank=True, max_length=100)),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('cercle', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('nature_occupation_code', models.CharField(blank=True, max_length=50)),
                ('nature_occupation_libelle', models.CharField(blank=True, max_length=255)),
                ('zone_amenagement', models.CharField(blank=True, max_length=100)),
                ('statut_foncier', models.CharField(blank=True, max_length=100)),
                ('origine', models.CharField(blank=True, max_length=100)),
                ('reference_plan', models.CharField(blank=True, max_length=50)),
                ('echelle_leve', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('date_derniere_maj', models.DateField(blank=True, null=True)),
                ('geometry', models.JSONField()),
            ],
            options={
                'db_table': 'parcelle_cadastrale',
                'ordering': ['id_parcelle'],
            },
        ),
    ]
