# Generated by Django 6.0.7 on 2026-08-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0013_align_couche_routes_equipements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParcelleCadastrale',
        ),
        migrations.RunSQL(
            'DROP TABLE IF EXISTS "highway"; DROP TABLE IF EXISTS "amenity";',
            'CREATE TABLE IF NOT EXISTS "highway" (id BIGSERIAL PRIMARY KEY);'
            'CREATE TABLE IF NOT EXISTS "amenity" (id BIGSERIAL PRIMARY KEY);',
        ),
    ]
