# Generated by Django 6.0.7 on 2026-08-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0015_seed_donnees_couches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('filtres', models.JSONField(blank=True, null=True)),
                ('poids_amc', models.DecimalField(decimal_places=2, default=0.7, max_digits=5)),
                ('poids_rentabilite', models.DecimalField(decimal_places=2, default=0.3, max_digits=5)),
                ('nombre_parcelles', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('complete', 'Complète'), ('en_cours', 'En cours'), ('erreur', 'Erreur')], default='complete', max_length=20)),
                ('projet', models.ForeignKey(db_column='projet_id', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='projets.projet')),
            ],
            options={
                'db_table': 'analyse',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parcelle', models.CharField(max_length=50)),
                ('nom', models.CharField(blank=True, default='', max_length=150)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('score_accessibilite', models.IntegerField(blank=True, null=True)),
                ('score_positionnement', models.IntegerField(blank=True, null=True)),
                ('score_topographie', models.IntegerField(blank=True, null=True)),
                ('score_superficie', models.IntegerField(blank=True, null=True)),
                ('score_amc', models.FloatField(blank=True, null=True)),
                ('roi', models.FloatField(blank=True, null=True)),
                ('marge', models.FloatField(blank=True, null=True)),
                ('benefice_net', models.FloatField(blank=True, null=True)),
                ('prix_terrain', models.FloatField(blank=True, null=True)),
                ('score_rentabilite', models.FloatField(blank=True, null=True)),
                ('type_rentabilite', models.CharField(blank=True, default='', max_length=20)),
                ('score_final', models.FloatField(blank=True, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('nombre_criteres_satisfaits', models.IntegerField(default=0)),
                ('total_criteres', models.IntegerField(default=0)),
                ('criteres', models.JSONField(blank=True, null=True)),
                ('points_forts', models.JSONField(blank=True, null=True)),
                ('points_faibles', models.JSONField(blank=True, null=True)),
                ('analyse', models.ForeignKey(db_column='analyse_id', on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='projets.analyse')),
            ],
            options={
                'db_table': 'resultat_analyse',
                'ordering': ['rang'],
            },
        ),
    ]
