# Generated by Django 6.0.7 on 2026-08-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0017_analyse_resultatanalyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatanalyse',
            name='reference_cadastrale',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
