# Generated by Django 6.0.7 on 2026-08-13 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_derniere_connexion'),
        ('projets', '0019_remplacer_couche_cadastre'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='terrain',
            name='consistance',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='terrain',
            name='fid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrain',
            name='geometry',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='terrain',
            name='indice',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='terrain',
            name='num_parcelle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='terrain',
            name='utilisateur',
            field=models.ForeignKey(blank=True, db_column='utilisateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terrains_ajoutes', to='accounts.utilisateur'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
