# Generated by Django 6.0.7 on 2026-08-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0021_supprimer_rentabilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='poids_amc',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='poids_rentabilite',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=5),
        ),
    ]
