# Generated by Django 5.0.3 on 2026-08-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0024_clear_mnt_attributs'),
        ('projets', '0024_terrain_geometry_polygon_champs_descriptifs'),
    ]

    operations = [
    ]
