# Generated by Django 6.0.7 on 2026-08-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0024_terrain_geometry_polygon_champs_descriptifs'),
        ('projets', '0025_ajouter_champs_rentabilite'),
    ]

    operations = [
    ]
