# Generated by Django 5.0.3 on 2026-08-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0025_merge_20260818_1506'),
        ('projets', '0026_merge_20260818_1514'),
    ]

    operations = [
    ]
