# Generated by Django 6.0.7 on 2026-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0026_merge_20260818_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='rentabilite_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
