# Generated by Django 6.0.7 on 2026-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0027_add_rentabilite_json_to_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatanalyse',
            name='criteres_conformite',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
