# Generated by Django 5.0.3 on 2026-08-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0027_add_rentabilite_json_to_terrain'),
        ('projets', '0027_merge_20260818_1707'),
    ]

    operations = [
    ]
