# Generated by Django 5.0.3 on 2026-08-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0028_add_criteres_conformite'),
        ('projets', '0028_merge_20260824_1249'),
    ]

    operations = [
    ]
