# Generated by Django 6.0.7 on 2026-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0029_merge_20260824_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='has_equipement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='prix_vente_equipement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='surface_equipement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
