# Generated by Django 6.0.7 on 2026-08-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0030_projet_has_equipement_projet_prix_vente_equipement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='cout_construction_equipement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='quote_part_equipement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
