# Generated by Django 5.0.3 on 2026-08-25 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0032_importer_donnees_couches'),
    ]

    operations = [
        migrations.CreateModel(
            name='PonderationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrice_ahp', models.JSONField(default=list, help_text='3 comparaisons par paires [a12, a13, a23]')),
                ('ordres_roc', models.JSONField(default=dict, help_text='{"accessibilite": ["Enseignement", "Routes", ...], "positionnement": [...]}')),
                ('selections_criteres', models.JSONField(default=dict, help_text='{"accessibilite": ["enseignement", "sante", "routes"], "localisation": ["centre_ville"], ...}')),
                ('preferences_localisation', models.JSONField(default=dict, help_text='{"localisation": "centre_ville", "situation_administrative": "intra_perimetre"}')),
                ('preferences_pente', models.JSONField(default=list, help_text='["0_5", "5_10"]')),
                ('seuil', models.FloatField(default=0.3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(db_column='projet_id', on_delete=django.db.models.deletion.CASCADE, related_name='ponderation_preferences', to='projets.projet')),
            ],
            options={
                'db_table': 'ponderation_preference',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
    ]
