# Generated by Django 5.0.3 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0032_ponderationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponderationpreference',
            name='ordre_categories',
            field=models.JSONField(blank=True, default=list, help_text="[cat_rang1, cat_rang2, cat_rang3] ordre choisi par l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='ponderationpreference',
            name='matrice_ahp',
            field=models.JSONField(default=list, help_text='2 intensités consécutives [a12, a23] (a13 = a12×a23 déduit)'),
        ),
    ]
