# Generated by Django 6.0.7 on 2026-08-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0033_add_ordre_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='cout_construction_equipement_prive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='has_equipement_prive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='prix_vente_equipement_prive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='quote_part_equipement_prive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='projet',
            name='surface_equipement_prive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
