# Generated by Django 5.0.3 on 2026-08-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0033_add_ordre_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='derniere_maj_geo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrain',
            name='pente_calculee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrain',
            name='zone_localisation_calculee',
            field=models.CharField(blank=True, choices=[('centre_ville', 'Centre-ville'), ('periurbaine', 'Périphérie')], default='', max_length=20),
        ),
    ]
