# Generated by Django 6.0.7 on 2026-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0034_equipement_prive'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='surface_constructible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='surface_espace_vert',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='surface_voie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
