# Generated by Django 6.0.7 on 2026-08-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0035_projet_surface_constructible_and_more'),
        ('projets', '0036_importer_limites_admin'),
    ]

    operations = [
    ]
