# Generated by Django 6.0.7 on 2026-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0037_merge_20260827_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponderationpreference',
            name='preferences_localisation',
            field=models.JSONField(default=dict, help_text='{"localisation": "centre_ville"}'),
        ),
    ]
