# Generated by Django 6.0.7 on 2026-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0039_parametreaffectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametreaffectation',
            name='categorie',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='code',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Désignation / Code'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='cos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='COS'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='cus',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='CUS / CES'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='hauteur_max',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hauteur max (m)'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='largeur_min',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Largeur min'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='nombre_etages',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nombre d'étages"),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Source réglementaire'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='statut',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='surface_min',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Surface min'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='type_construction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de construction'),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='type_operation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Type d'opération"),
        ),
        migrations.AlterField(
            model_name='parametreaffectation',
            name='zone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Zone'),
        ),
    ]
